### ISSUE TITLE
Compatible with Ansible 2.3.x

### ISSUE THREAD

**Issue by chilcano** [chouseknecht/minishift-up-role#5]
Unfortunately I cannot use this role with Ansible 2.3.x in OSX.
Ansible 2.4 is nor available in Pip.
```
$ pip list --format=columns | grep -e ansible -e Jinja
ansible           2.3.2.0
Jinja2            2.9.6
```

The problem is related to `include_tasks`, I've changed it to `include` and worked. Now I'm facing other problem when creating the route by using previously copied `oc` in `/usr/local/bin/`. I had to tweak the `copy_oc_client.yml`, specifically this:
```
- name: Copy oc client
  copy:
    src: "{{ latest_version.path }}/oc"
    dest: "{{ openshift_client_dest }}/oc"
    remote_src: yes
    mode: 0755
#  become: yes
#  become_user: root
```
Finally, I had this error:

```
TASK [/Users/Chilcano/1github-repo/houseknecht/minishift-up-role : Create the route] *********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["oc", "create", "-f", "route.yml"], "delta": "0:00:00.115770", "end": "2017-09-07 11:35:33.178153", "failed": true, "rc": 1, "start": "2017-09-07 11:35:33.062383", "stderr": "error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:\n\n  1. Via the command-line flag --config\n  2. Via the KUBECONFIG environment variable\n  3. In your home directory as ~/.kube/config\n\nTo view or setup config directly use the 'config' command.", "stderr_lines": ["error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:", "", "  1. Via the command-line flag --config", "  2. Via the KUBECONFIG environment variable", "  3. In your home directory as ~/.kube/config", "", "To view or setup config directly use the 'config' command."], "stdout": "", "stdout_lines": []}
```
Any idea?
Regards.

**Comment by chilcano** [comment]
I've downloaded latest version this Role,  and the error is related to `oc` permissions.
```
TASK [/Users/Chilcano/1github-repo/minishift-up-role : Login as system:admin] *************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "oc login -u system:admin", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
	to retry, use: --limit @/Users/Chilcano/1github-repo/minishift-up-role/minishift-up.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************************************
localhost                  : ok=29   changed=11   unreachable=0    failed=1
```

Regards.

**Comment by chilcano** [comment]
I've made it work. Below the steps.

- I've used Ansible 2.3.x on OSX.
- I've used latest version this role (Tag v1.0.7.2).
- I've changed `include_tasks` for `include`
- I've updated `main.yml`.

```
...
- name: Cleanup output file
  file:
    path: /tmp/minishift.out
    state: absent

##### [xyz] 
#- name: Give cluster-admin to developer
#  include: grant_admin.yml

- name: Check if oc binary exists
  stat:
    path: "{{ openshift_client_dest }}/oc"
  register: oc_client

- name: Copy latest oc client from ~/.minishift
  include: copy_oc_client.yml
  when: not oc_client.stat.exists or openshift_force_client_copy

- name: Create objects
  include: create_objects.yml

##### moved from [xyz]
- name: Give cluster-admin to developer
  include: grant_admin.yml

- name: Add entry to /etc/hosts
  include: add_hostname.yml
...
```
Regards.
